#!/bin/sh

set -eu

SOLANA_PROGRAMS=("sum" "square")

case "$1" in
  "reset")
    rm -rf client/node_modules
    for deployed_program in $(solana program show --programs | grep '^[a-zA-Z0-9]\{44\}' | cut -d' ' -f1); do
      if [[ $deployed_program != "Program" ]]; then
        echo $program:
        solana program close $deployed_program
      fi
    done
    rm -rf dist/program
    ;;
  "clean")
    rm -rf client/node_modules
    for program in "${SOLANA_PROGRAMS[@]}"; do
      echo $program:
      (cd "$program" && cargo clean)
    done
    ;;
  "build")
    for program in "${SOLANA_PROGRAMS[@]}"; do
      echo $program:
      (cd "$program" && cargo build-sbf --sbf-out-dir=../dist/program)
    done
    ;;
  "deploy")
    for program in "${SOLANA_PROGRAMS[@]}"; do
      echo $program:
      (
        set eu
        cd "$program"
        cargo build-sbf --sbf-out-dir=../dist/program
        solana program deploy "dist/program/$program.so"
      )
    done
    ;;
esac
